CREATE TABLE [dbo].[Country]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] NVARCHAR(50) NOT NULL,
	[DateCreated] DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    [Deleted] BIT NOT NULL DEFAULT 0, 
)
